config/routes.rb
Rails.application.routes.draw do
  resources :restaurants do
    member do
      get :publish
    end
  end
  devise_for :users
  get 'pages/home'

  get 'pages/about'

  get 'pages/contact'

  get 'pages/data'

  root 'pages#home'

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  geocoded_by :address   # can also be an IP address
  after_validation :geocode

  mount_uploaders :images, ImageUploader

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @restaurants = Restaurant.where(published: true)
    @hash = Gmaps4rails.build_markers(@restaurants) do |restaurant, marker|
      marker.lat restaurant.latitude
      marker.lng restaurant.longitude
      marker.picture({
        :url => "/chili-drop.png",
        :width   => 65,
        :height  => 65
      })
      marker.infowindow render_to_string(:partial => "/restaurants/infobox", :locals => { :restaurant => restaurant})
      marker.title restaurant.name
      marker.json({ :id => restaurant.id, :name => restaurant.name})
    end
    if request.location.ip == '::1'
      @location = request.safe_location
      rest_count = Restaurant.near([34.0900310, -118.3688430], 0.5, :units => :km).map{|a| a}.count
    else
      @location = request.safe_location
      rest_count = Restaurant.near([@location.latitude, @location.longitude], 1, :units => :km).map{|a| a}.count
    end
    if rest_count > 0
      @near_me = "yes"
    else
      @near_me = ""
    end
  end

  def about
  end

  def contact
  end

  def data
    restaurant = Restaurant.find(params[:restaurant][:id])
    respond_to do |format|
      format.json { render json: restaurant}# respond with the created JSON object
    end
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy, :publish]

  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.all
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def publish
    @restaurant.published = @restaurant.published ? false : true
    @restaurant.save
    redirect_to restaurants_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :description, :address, :phone, :website, :latitude, :longitude, :category, {images: []})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
  def category
    ["Sit Down", "Take Out"]
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{charset: "utf-8"}
    %meta{content: "IE=edge", "http-equiv" => "X-UA-Compatible"}
    %meta{content: "width=device-width, initial-scale=1", name: "viewport"}
    %meta{content: "", name: "description"}
    %meta{content: "", name: "author"}
    %script{:src => "//maps.google.com/maps/api/js?key=AIzaSyDzYPWSWVUkOfCrwFy7CFov4rzEKa93mo0"}
    %script{:src => "//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"}
    %script{:src => "//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js", :type => "text/javascript"}
    / only if you need custom infoboxes

    %title Tortilla Maps

    / HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
    /[if lt IE 9]
      = javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js"

    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-inverse.navbar-fixed-top{role: "navigation"}
      .container
        .navbar-header
          %button.navbar-toggle.collapsed{type: "button", data: {toggle: "collapse", target: "#navbar"}, aria: {expanded: "false", controls: "navbar"} }
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to "/", class: "navbar-brand", style: "padding:0px;" do
            .pull-left=image_tag("/logo.png", style:"max-width:100px;")
            .pull-left
              .tagline
                "Mexican Food in LA Mapped"
            .clearfix
        #navbar.collapse.navbar-collapse
          %ul.nav.navbar-nav
            -if current_user
              %li=link_to "Restaurants", restaurants_path()
    -unless current_page? root_path
      .container
        = yield
    -else
      .container-fluid{style:"padding:0;"}
        - flash.each do |name, msg|
          = content_tag :div, class: "alert alert-#{name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do
            %button.close{type: "button", data: {dismiss: "alert"} }
              %span{aria: {hidden: "true"} } &times;
              %span.sr-only Close
            = msg
        = yield
    :coffeescript
      $(document).ready ->
        $(".fancybox")
          .attr('rel', 'gallery')
          .fancybox({
              padding : 0
          });

app/views/pages/_restaurant_info.html.haml
#restaurantModal.modal.fade{"aria-labelledby" => "restaurantModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %button.close.trigger-click{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button", data: { event_name: 'Close Pop-up'}}
          %span{"aria-hidden" => "true"} ×
        #myModalLabel.modal-title
          %h1.restaurant-name
      .modal-body
        .restaurant-description
        %h4
          %span
            =image_tag("/yellow-chili.png", style:"max-width:20px;position: relative;bottom: 5px;")
          %span.restaurant-address
        %p.restaurant-hours

        .row
          .no-restaurant{style:"display:none;"}
            .col-xs-12
              %p
                Sorry fellow taco lovers, right now we do not have any food pics. Do you have any? Let us know at tacolovers@tortillamaps.com
          

          .restaurant-images



          .col-xs-12
            %a.fancybox.image-1{:href => "", :rel => "gallery"}
              .btn.btn-taco
                Show Me The Rest of The Food >>

app/views/pages/about.html.haml
.page-header
  %h1 Pages#about
%p Find me in app/views/pages/about.html.haml

app/views/pages/contact.html.haml
.page-header
  %h1 Pages#contact
%p Find me in app/views/pages/contact.html.haml

app/views/pages/home.html.haml
#mappy{:style => "width: 100%;", :data => {:lat => "#{@location.latitude}", long: "#{@location.longitude}", near:"#{@near_me}"}}
  #map{:style => "width: 100%; height: 100%;height:100vh;"}
=render "restaurant_info"
:coffeescript
  middle =
    if $("#mappy").data("lat").length < 1 || $("#mappy").data("lat") == "0.0"
      new google.maps.LatLng(34.0900310, -118.3688430)
    else
      lat = parseFloat($("#mappy").data("lat"))
      long = parseFloat($("#mappy").data("long"))
      new google.maps.LatLng(lat, long)

  mapStyle = 
    [
      {
        'featureType': 'administrative.country'
        'elementType': 'geometry.stroke'
        'stylers': [
          { 'lightness': '40' }
          { 'visibility': 'on' }
        ]
      }
      {
        'featureType': 'administrative.country'
        'elementType': 'labels'
        'stylers': [
          { 'visibility': 'simplified' }
          { 'lightness': '20' }
        ]
      }
      {
        'featureType': 'administrative.province'
        'elementType': 'geometry.stroke'
        'stylers': [ { 'visibility': 'off' } ]
      }
      {
        'featureType': 'administrative.province'
        'elementType': 'labels'
        'stylers': [
          { 'visibility': 'simplified' }
          { 'lightness': '10' }
        ]
      }
      {
        'featureType': 'administrative.locality'
        'elementType': 'geometry.stroke'
        'stylers': [ { 'visibility': 'on' } ]
      }
      {
        'featureType': 'administrative.locality'
        'elementType': 'labels'
        'stylers': [
          { 'visibility': 'simplified' }
          { 'lightness': '25' }
        ]
      }
      {
        'featureType': 'landscape'
        'elementType': 'all'
        'stylers': [
          { 'hue': '#ffbb00' }
          { 'saturation': 43.400000000000006 }
          { 'lightness': 37.599999999999994 }
          { 'gamma': 1 }
        ]
      }
      {
        'featureType': 'poi'
        'elementType': 'all'
        'stylers': [
          { 'hue': '#00FF6A' }
          { 'saturation': -1.0989010989011234 }
          { 'lightness': 11.200000000000017 }
          { 'gamma': 1 }
        ]
      }
      {
        'featureType': 'road'
        'elementType': 'geometry'
        'stylers': [
          { 'visibility': 'on' }
          { 'lightness': '30' }
        ]
      }
      {
        'featureType': 'road.highway'
        'elementType': 'all'
        'stylers': [
          { 'hue': '#FFC200' }
          { 'saturation': -61.8 }
          { 'lightness': 45.599999999999994 }
          { 'gamma': 1 }
        ]
      }
      {
        'featureType': 'road.arterial'
        'elementType': 'all'
        'stylers': [
          { 'hue': '#FF0300' }
          { 'saturation': -100 }
          { 'lightness': 51.19999999999999 }
          { 'gamma': 1 }
        ]
      }
      {
        'featureType': 'road.local'
        'elementType': 'all'
        'stylers': [
          { 'hue': '#FF0300' }
          { 'saturation': -100 }
          { 'lightness': 52 }
          { 'gamma': 1 }
        ]
      }
      {
        'featureType': 'water'
        'elementType': 'all'
        'stylers': [
          { 'hue': '#00ffda' }
          { 'saturation': '-50' }
          { 'lightness': '25' }
          { 'gamma': 1 }
        ]
      }
      {
        'featureType': 'water'
        'elementType': 'labels'
        'stylers': [
          { 'visibility': 'off' }
          { 'lightness': '30' }
        ]
      }
    ]
  handler = Gmaps.build('Google')
  handler.buildMap {
    provider: {styles:mapStyle, center: middle, zoom: 14}
    internal: id: 'map'
    markers: { clusterer: null}
  }, ->
    markers = #{raw @hash.to_json}
    Gmaps.store = {}
    Gmaps.store.markers = markers.map((m) ->
      marker = handler.addMarker(m, animation: google.maps.Animation.DROP)
      marker.serviceObject.set 'id', m.id
    
      google.maps.event.addListener marker.serviceObject, 'click', ->
        marker = this
        console.log 'Tite for this marker is:' + @title
        Gmaps.bounceMarker(m.id)
        Gmaps.selectMarker(m.id)
      marker
    )
    if $("#mappy").data("near").length < 1
      handler.bounds.extendWith Gmaps.store.markers
      handler.fitMapToBounds()

    Gmaps.bounceMarker = (id) ->
      $.each Gmaps.store.markers, ->
        if @serviceObject.id == id
          #@panTo()
          @serviceObject.setAnimation 4
        else
          @serviceObject.setAnimation null
    
    Gmaps.selectMarker = (id) ->
      $.ajax
        dataType: 'text'
        url: '/pages/data.json'
        type: 'GET'
        data: restaurant:
          id: id
        success: (json) ->
          result = $.parseJSON(json)
          $(".restaurant-name").html(result["name"])
          if result["description"] != null
            $(".restaurant-description").html("<h3>"+result["description"]+"</h3><br>")
          else
            $(".restaurant-description").html(" ")
          $(".restaurant-address").html(result["address"])
          if result["hours"] != null
            $(".restaurant-hours").html("<hr>"+result["hours"]+"<hr>")
          else
            $(".restaurant-hours").html(" ")
          if result["images"].length < 1
            $(".restaurant-images").html("")
            $(".no-restaurant").show()
            $(".image-1").hide()
          else
            $(".image-1").show()
            $(".image-1").attr('href', result["images"][0]["url"])
            $(".no-restaurant").hide()
            $(".restaurant-images").html("")
            for c, i in result["images"]
              if i != 0
                $(".restaurant-images").append("<div class='col-xs-12 col-sm-6 restaurant-image'><a href="+c.url+" class='fancybox image-box' rel='gallery'><div style='background:url("+c.url+");background-size: cover;' class='image-box'></div></a></div>")






      $('#restaurantModal').modal('show')

app/views/restaurants/_form.html.haml
= form_for @restaurant, html: { class: "form-horizontal", role: "form" } do |f|
  -if @restaurant.errors.any?
    .alert.alert-danger.alert-dismissable{role: "alert"}
      %button.close{type: "button", data: {dismiss: "alert"} }
        %span{aria: {hidden: "true"} } &times;
        %span.sr-only Close
      %h4= "#{pluralize(@restaurant.errors.count, "error")} prohibited this restaurant from being saved:"

      %ul
        - @restaurant.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :name, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :description, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_area :description, class: 'form-control'
  .form-group
    = f.label :address, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_area :address, class: 'form-control'
  .form-group
    = f.label :phone, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :phone, class: 'form-control'
  .form-group
    = f.label :website, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :website, class: 'form-control'
  .form-group
    = f.label :latitude, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :latitude, class: 'form-control'
  .form-group
    = f.label :longitude, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :longitude, class: 'form-control'
  .form-group
    = f.label :category, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.select :category, category, {}, {class: "form-control"}
  .form-group
    = f.label :images, class: 'col-sm-2 control-label'
    .col-sm-10
      =f.file_field :images, multiple: true
      = f.hidden_field :images_cache
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit class: 'btn btn-primary'

app/views/restaurants/_infobox.html.haml
.infobox
  %h1
    %span
      =image_tag("/cactus.png", style:"max-width:20px;position: relative;bottom: 7px;")
    =restaurant.name
  .hide
    %h3
      =restaurant.description
    %br
    %h4
      %span
        =image_tag("/yellow-chili.png", style:"max-width:20px;position: relative;bottom: 5px;")
      =restaurant.address
    -if restaurant.images.count > 0
      .row
        .col-xs-12
          %a.fancybox{:href => "#{restaurant.images.first}", :rel => "group"}
            .btn.btn-taco
              Show Me The Food >>

          -restaurant.images.drop(1).each do |image|
            %a.fancybox{:href => image.url, rel: "group", style: "display:none;"}
    
.arrow-down

app/views/restaurants/edit.html.haml
.page-header
  = link_to restaurants_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to @restaurant, class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-info-sign
    Show
  %h1 Editing restaurant

= render 'form'

app/views/restaurants/index.html.haml
.page-header{style:"margin-top:80px;"}
  .form-group
    %input.search.form-control{:placeholder => "Type to Search. It works across all columns", :type => "text"}/

  = link_to new_restaurant_path, class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-plus
    New Restaurant
  %h1 Listing restaurants

.table-responsive
  %table.results.table-hover.table-bordered.table{"data-toggle" => "table"}
    %thead
      %tr
        %th{"data-sortable" => "true"} Name
        %th{"data-sortable" => "true"} Description
        %th{"data-sortable" => "true"} Address
        %th{"data-sortable" => "true"} Phone
        %th{"data-sortable" => "true"} Website
        %th{"data-sortable" => "true"} Latitude
        %th{"data-sortable" => "true"} Longitude
        %th{"data-sortable" => "true"} Google Link
        %th{"data-sortable" => "true"} Hours
        %th{"data-sortable" => "true"} Published?
        %th
        %th
        %th
        %th

    %tbody
      - @restaurants.each do |restaurant|
        %tr
          %td= restaurant.name
          %td= restaurant.description
          %td= restaurant.address
          %td= restaurant.phone
          %td= restaurant.website
          %td= restaurant.latitude
          %td= restaurant.longitude
          %td
            = link_to "Find on Google", "https://www.google.com/search?q=#{restaurant.name}+Mexican+Restaurant+Los+Angeles&oq=Tortilla+Republic+Weho+Mexican+Restaurant+Los+Angeles", target: "blank"
          %td= restaurant.hours
          %td= restaurant.published
          -if restaurant.published
            %td= link_to 'unPublish', publish_restaurant_path(restaurant)
          -else
            %td= link_to 'Publish', publish_restaurant_path(restaurant)
          %td= link_to 'Show', restaurant
          %td= link_to 'Edit', edit_restaurant_path(restaurant)
          %td= link_to 'Destroy', restaurant, data: { confirm: 'Are you sure?' }, method: :delete
:javascript
  $(document).ready(function() {
    $(".search").keyup(function () {
      var searchTerm = $(".search").val();
      var listItem = $('.results tbody').children('tr');
      var searchSplit = searchTerm.replace(/ /g, "'):containsi('")
      
    $.extend($.expr[':'], {'containsi': function(elem, i, match, array){
          return (elem.textContent || elem.innerText || '').toLowerCase().indexOf((match[3] || "").toLowerCase()) >= 0;
      }
    });
      
    $(".results tbody tr").not(":containsi('" + searchSplit + "')").each(function(e){
      $(this).hide();
    });

    $(".results tbody tr:containsi('" + searchSplit + "')").each(function(e){
      $(this).show();
    });

    var jobCount = $('.results tbody tr[visible="true"]').length;

    if(jobCount == '0') {$('.no-result').show();}
      else {$('.no-result').hide();}
    });
  });

app/views/restaurants/new.html.haml
.page-header
  = link_to restaurants_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  %h1 New restaurant

= render 'form'

app/views/restaurants/show.html.haml
.page-header
  = link_to restaurants_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to edit_restaurant_path(@restaurant), class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-pencil
    Edit
  %h1 Show restaurant

%dl.dl-horizontal
  %dt Name:
  %dd= @restaurant.name
  %dt Description:
  %dd= @restaurant.description
  %dt Address:
  %dd= @restaurant.address
  %dt Phone:
  %dd= @restaurant.phone
  %dt Website:
  %dd= @restaurant.website
  %dt Latitude:
  %dd= @restaurant.latitude
  %dt Longitude:
  %dd= @restaurant.longitude
  %dt Category:
  %dd= @restaurant.category
  %dt Images:
  .row
    -@restaurant.images.each do |image|
      .col-xs-4{style: "max-height:200px;overflow:hidden;"}
        %a.fancybox{:href => image}
          .food-image{style:"background: url(#{image}) no-repeat center center;-webkit-background-size: cover;-moz-background-size: cover;-o-background-size: cover;background-size: cover;height:200px;width:200px;"}